[package]
name = "c166-asm"
version = "0.1.5"
authors = ["Alex Zepeda <c166@inferiorhumanorgans.com>"]

[dependencies]
c166-core = { path = "../c166-core" }

[lib]
name = "c166_asm"
crate-type = ["cdylib"]
