[package]
name = "c166-asm"
version = "0.2.0"
authors = ["Alex Zepeda <c166@inferiorhumanorgans.com>"]

[dependencies]
c166-core = { path = "../c166-core" }
lazy_static = "1.0"

[lib]
name = "c166_asm"
crate-type = ["cdylib"]
