[package]
name = "c166-analysis"
version = "0.1.5"
authors = ["Alex Zepeda <c166@inferiorhumanorgans.com>"]

[dependencies]
c166-core = { path = "../c166-core" }
libc = "0.2"
runtime-fmt = "*"

[lib]
name = "c166_analysis"
crate-type = ["cdylib"]
