[package]
name = "c166-core"
version = "0.1.5"
authors = ["Alex Zepeda <c166@inferiorhumanorgans.com>"]

[build-dependencies]
bindgen = "~ 0.37"

[dependencies]
libc = "*"
byteorder = "1"
enum-primitive-derive = "^0.1"
num-traits = "^0.1"
bitflags = "1.0"
