[package]
name = "c166-bin"
version = "0.2.0"
authors = ["Alex Zepeda <alex@inferiorhumanorgans.com>"]

[dependencies]
c166-core = { path = "../c166-core" }

[lib]
name = "c166_bin"
crate-type = ["cdylib"]
